# Generated by Django 3.0.7 on 2020-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='txt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
